### imports:

In [29]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os


## Read Files

In [30]:
test_df = pd.read_csv("test.csv")
train_df = pd.read_csv("train.csv")
submit_df = pd.read_csv("sample_submission.csv")
test_df

id  delta  stop_0  stop_1  stop_2  stop_3  stop_4  stop_5  stop_6  \
0      50000      5       0       0       1       0       0       0       0   
1      50001      5       0       0       0       0       0       0       0   
2      50002      1       0       1       0       0       1       0       0   
3      50003      2       0       0       0       0       0       0       0   
4      50004      3       0       0       0       0       0       0       0   
...      ...    ...     ...     ...     ...     ...     ...     ...     ...   
49995  99995      4       0       0       0       0       0       0       0   
49996  99996      2       0       0       1       0       0       0       0   
49997  99997      4       0       0       0       0       0       0       0   
49998  99998      1       0       0       1       1       0       0       0   
49999  99999      1       0       0       1       0       0       0       0   

       stop_7  ...  stop_615  stop_616  stop_617  stop_618  stop_619  \
0           0  ...         0         0         0         0         1   
1           1  ...         0         0         1         1         0   
2           0  ...         1         1         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
49995       0  ...         0         0         0         0         0   
49996       0  ...         0         0         0         0         0   
49997       0  ...         0         0         0         0         0   
49998       1  ...         0         0         0         0         0   
49999       0  ...         0         0         0         0         0   

       stop_620  stop_621  stop_622  stop_623  stop_624  
0             0         1         0         0         1  
1             1         0         0         0         0  
2             0         1         0         1         0  
3             0         0         1         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
49995         0         0         0         0         0  
49996         0         0         0         0         0  
49997         0         0         0         0         0  
49998         0         0         0         0         0  
49999         0         0         0         1         1  

[50000 rows x 627 columns]

In [37]:
def gameOfLife(board) -> None:
    
    neighbors = [(1,0), (1,-1), (0,-1), (-1,-1), (-1,0), (-1,1), (0,1), (1,1)]

    rows = len(board)
    cols = len(board[0])

        # Iterate through board cell by cell.
    for row in range(rows):
        for col in range(cols):

                # For each cell count the number of live neighbors.
            live_neighbors = 0
            for neighbor in neighbors:

                    # row and column of the neighboring cell
                r = (row + neighbor[0])
                c = (col + neighbor[1])

                    # Check the validity of the neighboring cell and if it was originally a live cell.
                if (r < rows and r >= 0) and (c < cols and c >= 0) and abs(board[r][c]) == 1:
                    live_neighbors += 1

                # Rule 1 or Rule 3
            if board[row][col] == 1 and (live_neighbors < 2 or live_neighbors > 3):
                    # -1 signifies the cell is now dead but originally was live.
                board[row][col] = -1
                # Rule 4
            if board[row][col] == 0 and live_neighbors == 3:
                    # 2 signifies the cell is now live but was originally dead.
                board[row][col] = 2

        # Get the final representation for the newly updated board.
    for row in range(rows):
        for col in range(cols):
            if board[row][col] > 0:
                board[row][col] = 1
            else:
                board[row][col] = 0

def main():
    print('Enter the id number you want to solve:')
    id = input()
    print('Your entered id is ' + id)
    id = int(id)
    print(f'test id: {id}')
    start_data = list(map(int,train_df.loc[id][2:627]))
    board = np.array(start_data).reshape(25,25)
    print(board)
    print('How many steps of revolution you want to make?')
    delta = list(train_df.delta)[id]
    print('current delta is '+ str(delta)+ '. Do you want change it? [y/n]')
    yorn = input()
    if yorn == 'y':
        print('Please enter your delta number')
        delta = input()
        delta = int(delta)
        
    print(f"after {delta} times evolution: ")
    while delta!=0:
        gameOfLife(board)
        delta-=1
    
    print(board)

main()


Enter the id number you want to solve:
1
Your entered id is 1
test id: 1
[[0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 1]
 [1 1 1 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 